site_name: Calcifer
build:
  image: latest
theme:
  name: 'material'
python:
  version: 3.6
  setup_py_install: true
# Don't build any extra formats
formats: []
# Build PDF & ePub
formats:
    - epub
    - pdf


nav:
  - Home: index.md
  - Get Started: start.md
  - Database:
    - Intorduction: db/index.md
    - Tables: db/tables.md
  - APIs:
    - Intorduction: apis/index.md
    - Rest APIs: apis/rest.md
  - External Libs:
    - Introduction: libs/index.md
    - Time: libs/time.md
    - Kave Negar: libs/kavenegar.md
    - Zarin Pal: libs/zarinpal.md
  - Terms Of Use: terms.md